#ifndef _PHYSICS_EVENT_H_
#define _PHYSICS_EVENT_H_

#include "EventHits.h"

/**
 * @class PhysicsEvent
 * @brief Container for physics event generated by factory
 * 
 * Contains event number and associated detector hits for a single physics event.
 */
class PhysicsEvent {
    
private:
    int event_num;
    std::shared_ptr<EventHits> hits;
    
public:
    /**
     * @brief Default constructor
     * Initializes event number to -1 and hits to nullptr
     */
    PhysicsEvent()
        : event_num(-1), hits(nullptr) {}

    /**
     * @brief Constructor
     * @param event_num Event number
     * @param hits Shared pointer to EventHits containing detector data
     */
    PhysicsEvent(int event_num, std::shared_ptr<EventHits> hits)
        : event_num(event_num), hits(std::move(hits)) {}


    int GetEventNumber() const {
        return event_num;
    }

    int SetEventNumber(int event_num) {
        this->event_num = event_num;
        return this->event_num;
    }

    std::shared_ptr<EventHits> SetHits(std::shared_ptr<EventHits> hits) {
        this->hits = hits;
        return this->hits;
    }

    void insertHitsIntoEvent(JEvent& event) const {
        hits->insertIntoEvent(event);
    }
};

#endif // _PHYSICS_EVENT_H_